queue_rules:
  - name: duplicated default from Merge PRs using label (rebase)
    queue_conditions:
      - label=dependencies
      - base=main
      - label=ready-to-merge-rebase
      - base=main
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - "#review-threads-unresolved=0"
    merge_conditions: []
    merge_method: rebase
  - name: duplicated default from Merge PRs using label (squash)
    queue_conditions:
      - label=dependencies
      - base=main
      - label=ready-to-merge-squash
      - base=main
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - "#review-threads-unresolved=0"
    merge_conditions: []
    merge_method: squash
  - name: default
    queue_conditions:
      - label=dependencies
      - base=main
    merge_conditions: []
    merge_method: squash

pull_request_rules:
  - name: Merge PRs using label (rebase) + Merge PRs using label (squash) + Merge
      dependency-update PRs
    conditions: []
    actions:
      queue:
