services:
  jabble:
    image: jabble:latest
    container_name: jabble
    ports:
      - "8081:8081"
    environment:
      - SESSION_SECRET=super-duper-s3cret
      - HONEYPOT_SECRET=super-duper-s3cret
      - INTERNAL_COMMAND_TOKEN=some-made-up-token
    command: ./startup.sh
    init: true # make ctrl+c work
    restart: no
