app = "sn"
primary_region = "cdg"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []
swap_size_mb = 1024

[[vm]]
size = 'shared-cpu-1x'
memory = '1GB'

[experimental]
allowed_public_ports = []
auto_rollback = true

[mounts]
source = "data"
destination = "/data"

[deploy]
release_command = "node ./other/sentry-create-release"


[http_service]
internal_port = 8081
force_https = true
# auto_stop_machines = "stop" # action when the app is idle for several minutes
# auto_start_machines = true
min_machines_running = 0

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/resources/healthcheck"
