// This file is generated by npm run build:icons

export type IconName =
	| 'chat-bubble'
	| 'minus-circled'
	| 'plus-circled'
	| 'target'
	| 'thick-arrow-down'
	| 'thick-arrow-up'
	| string // workaround until old icons are removed
